# Generated by Django 5.1.1 on 2024-09-08 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Название", max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("str", "Текст"),
                            ("int", "Число"),
                            ("choice", "Выбор значения"),
                        ],
                        help_text="Тип поля",
                        max_length=8,
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, help_text="Поле обязательное?"),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        help_text="Введите варианты через запятую",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FieldProfession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dynamic_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profession.dynamicfield",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Название", max_length=64)),
                ("description", models.TextField(help_text="Описание", max_length=512)),
                (
                    "extra_fields",
                    models.ManyToManyField(
                        through="profession.FieldProfession",
                        to="profession.dynamicfield",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="fieldprofession",
            name="profession",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profession.profession"
            ),
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=100)),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
                ("extra_fields", models.JSONField(blank=True, default=dict)),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profession.profession",
                    ),
                ),
            ],
        ),
    ]
